baseurl = "http://generationsmontessoricville.org"
languageCode = "en-us"
title = "Generations Montessori School Charlottesville"
subtitle = ""
theme = "gscv"

[params]
    sidebartitle = "Generations Montessori"
    sidebartagline = "Charlottesville, VA"
    nodate = true
    noauthor = true
    noread = true
    nopaging=true
    notoc=true

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180

[[menu.footer]]
