baseurl = "http://generationsmontessoricville.org"
languageCode = "en-us"
title = "Generations Montessori School Charlottesville"
subtitle = ""
theme = "gscv"

[params]
    sidebartitle = "Generations Montessori"
    sidebartagline = "Charlottesville, Virginia"
    nodate = true
    noauthor = true
    noread = true
    nopaging=true
    notoc=true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200

[[menu.footer]]
